### ISSUE TITLE
Alembic configuration

### ISSUE THREAD

**Issue by Euphorbium** [nsidnev/fastapi-realworld-example-app#2]
Is alembic configured correctly? When I change the model, and run `alembic revision`, it generates an empty migration. It does not seem to pick up the changes made in models files.

**Comment by nsidnev** [comment]
I've used alembic here only as tool for SQL migrations, not as migrations tool for sqlalchemy. Models in the `models` package are just [pydantic](https://pydantic-docs.helpmanual.io/) models (I've used [this](https://github.com/tiangolo/full-stack-fastapi-couchbase) as startpoint for project structure). I'll possibly add instead of raw queries [encode/orm](https://github.com/encode/orm) in future or totally replace alembic with yoyo-migrations package.

**Comment by bowuL** [comment]
> Is alembic configured correctly? When I change the model, and run `alembic revision`, it generates an empty migration. It does not seem to pick up the changes made in models files.

How did you resolve this migration problem afterwards?

**Comment by bowuL** [comment]
> 

emmm, so when i need to change the model struct, which way i can choose? I'm using this repo for my new project, only 5 days late have to submit...URGENT

**Comment by bowuL** [comment]
> 

emmm, so when i need to change the model struct, which way i can choose? I'm using this repo for my new project, only 5 days late have to submit...URGENT

**Comment by nsidnev** [comment]
I have not changed the way this project uses alembic, so the only way so far is to write migrations manually. See the existing migration for an example of how to do that.

**Comment by bowuL** [comment]
> 

Write migrations self?I can't find the definition for table structure,so how to modify table fields and run command to autogenerate migrations?emmm,now it seems unclear, may i need to change use salalchemy or anything else?

**Comment by nsidnev** [comment]
> I can't find the definition for table structure

The project structure can be found in the readme: https://github.com/nsidnev/fastapi-realworld-example-app#project-structure
This is the only migration that exists in this project: https://github.com/nsidnev/fastapi-realworld-example-app/blob/dc1aa666aa200f6a719bc4374aa8f2f94755e427/app/db/migrations/versions/fdf8821871d7_main_tables.py

> so how to modify table fields

Use operations from alembic to alter or modify tables/columns and write migrations with them: https://alembic.sqlalchemy.org/en/latest/ops.html

> run command to autogenerate migrations

You can't do that with this project because it simply doesn't use sqlalchemy to work with the database outside of migrations. The database part is built using aiosql, pypika and pydantic.

>  may i need to change use salalchemy

If you want to use sqlalchemy, you can adopt examples from the fastapi documentation by rewriting the database part of this project, or look for other examples that use fastapi, but this time with sqlalchemy. Perhaps this project just doesn't suit your needs.
